// packages/react/src/components/DynamicInput.tsx
import {
  FieldRendererProps,
  FieldTypeKey,
  makeErrorId,
  Properties,
} from '@dynamic-field-kit/core';
import React, { ReactNode, useMemo } from 'react';
import { getDefaultRenderer } from '../defaultRenderers';
import { useFieldRegistry } from '../FieldRegistryContext';

interface Props<T extends FieldTypeKey> {
  type: T;
  value?: unknown;
  onChange?: (value: unknown) => void;
  onBlur?: () => void;
  label?: string;
  placeholder?: string;
  options?: Properties[];
  className?: string;
  description?: ReactNode;
  disabled?: boolean;
  readOnly?: boolean;
  required?: boolean;
  touched?: boolean;
  dirty?: boolean;
  error?: string | string[];
  id?: string;
  ariaInvalid?: boolean;
  ariaDescribedBy?: string;
  ariaRequired?: boolean;
  min?: number | string;
  max?: number | string;
  step?: number | string;
  accept?: string;
  multiple?: boolean;
  /** Extra, framework-agnostic props forwarded verbatim to the renderer. */
  extraProps?: Properties;
}

const DynamicInputInner = <T extends FieldTypeKey>({
  type,
  onChange,
  onBlur,
  extraProps,
  ...rendererProps
}: Props<T>) => {
  const registry = useFieldRegistry();

  // Memoize renderer lookup to avoid unnecessary work on re-renders. Whether
  // it fell back to a default is tracked too: a custom renderer owns its own
  // error presentation, and emitting a second message would duplicate it.
  const { Renderer, isDefault } = useMemo(() => {
    const registered = registry.get(type) as
      React.ComponentType<FieldRendererProps> | undefined;
    return {
      Renderer: (registered ??
        getDefaultRenderer(type)) as React.ComponentType<FieldRendererProps>,
      isDefault: !registered,
    };
  }, [registry, type]);

  if (!Renderer) {
    return <div>Unknown field type: {type}</div>;
  }

  const { error, id } = rendererProps as FieldRendererProps;

  // Spread rather than re-listing each prop: the set is fixed by core's
  // FIELD_RENDERER_PROP_KEYS contract, and a hand-maintained list here is
  // exactly how `placeholder`, `min`, `max`, `step`, `accept` and `multiple`
  // came to be silently dropped on their way to the renderer.
  const control = React.createElement(Renderer, {
    ...extraProps,
    ...(rendererProps as FieldRendererProps),
    onValueChange: onChange,
    onBlur,
  });

  if (!isDefault || !error?.length || !id) {
    return control;
  }

  // A fragment, not a wrapper element: the message appears, but nothing about
  // the surrounding layout changes. The id is what `ariaDescribedBy` targets -
  // without this node that reference would dangle.
  return (
    <>
      {control}
      <div id={makeErrorId(id)} className="dfk-field-error" role="alert">
        {error[0]}
      </div>
    </>
  );
};

// Skip re-render when none of the rendered props actually changed, so
// unaffected fields don't re-render every time a sibling field's value changes.
// React.memo erases the generic signature, so restore it via an `unknown`
// round-trip (plain `as typeof DynamicInputInner` fails dts generation).
const DynamicInput = /* @__PURE__ */ React.memo(
  DynamicInputInner,
) as unknown as typeof DynamicInputInner;

export default DynamicInput;

// packages/svelte/src/components/DynamicInput.svelte
<script lang="ts">
  import {
    makeErrorId,
    type FieldTypeKey,
    type OptionsStatus,
    type Properties,
  } from '@dynamic-field-kit/core';
  import type { Component } from 'svelte';
  import { getDefaultRenderer } from '../defaultRenderers.js';
  import { useFieldRegistry } from '../fieldRegistryContext.js';

  // Every key of core's FIELD_RENDERER_PROP_KEYS must be declared here and
  // handed to the renderer below: scripts/check-renderer-prop-parity.js fails
  // the build when either list drifts from the contract.
  interface Props {
    type: FieldTypeKey;
    value?: unknown;
    onChange?: (value: unknown) => void;
    onBlur?: () => void;
    label?: string;
    placeholder?: string;
    required?: boolean;
    touched?: boolean;
    dirty?: boolean;
    options?: Properties[];
    optionsStatus?: OptionsStatus;
    optionsError?: unknown;
    className?: string;
    description?: unknown;
    disabled?: boolean;
    readOnly?: boolean;
    error?: string | string[];
    id?: string;
    ariaInvalid?: boolean;
    ariaDescribedBy?: string;
    ariaRequired?: boolean;
    min?: number | string;
    max?: number | string;
    step?: number | string;
    accept?: string;
    multiple?: boolean;
    /** Renderer-driven refetch for a search-remote field. */
    onOptionsQuery?: (query: string) => void;
    /** Extra, framework-agnostic props forwarded verbatim to the renderer. */
    extraProps?: Properties;
  }

  let {
    type,
    value,
    onChange,
    onBlur,
    label,
    placeholder,
    required,
    touched,
    dirty,
    options,
    optionsStatus,
    optionsError,
    className,
    description,
    disabled,
    readOnly,
    error,
    id,
    ariaInvalid,
    ariaDescribedBy,
    ariaRequired,
    min,
    max,
    step,
    accept,
    multiple,
    onOptionsQuery,
    extraProps,
  }: Props = $props();

  const registry = useFieldRegistry();
  const registered = $derived(
    registry.get(type) as Component<Record<string, unknown>> | undefined,
  );
  const Renderer = $derived(
    registered ??
      (getDefaultRenderer(type) as
        | Component<Record<string, unknown>>
        | undefined),
  );
  // This adapter accepts `error` as a string as well as an array, so index 0
  // of a raw string would be its first character.
  const firstError = $derived(Array.isArray(error) ? error[0] : error);
</script>

{#if Renderer}
  <Renderer
    {...extraProps}
    value={value}
    onValueChange={onChange}
    onBlur={onBlur}
    onOptionsQuery={onOptionsQuery}
    label={label}
    placeholder={placeholder}
    required={required}
    touched={touched}
    dirty={dirty}
    error={error}
    options={options}
    optionsStatus={optionsStatus}
    optionsError={optionsError}
    className={className}
    description={description}
    disabled={disabled}
    readOnly={readOnly}
    id={id}
    ariaInvalid={ariaInvalid}
    ariaDescribedBy={ariaDescribedBy}
    ariaRequired={ariaRequired}
    min={min}
    max={max}
    step={step}
    accept={accept}
    multiple={multiple}
  />
  <!--
    A custom renderer owns its own error presentation; a second message next
    to it would repeat what the consumer already shows. The id is what
    `ariaDescribedBy` points at.
  -->
  {#if !registered && firstError && id}
    <div id={makeErrorId(id)} class="dfk-field-error" role="alert">
      {firstError}
    </div>
  {/if}
{:else}
  <div>Unknown field type: {type}</div>
{/if}
