// packages/react/src/components/FieldInput.tsx
import { FieldDescription, Properties } from "@dynamic-field-kit/core"
import DynamicInput from "./DynamicInput"

interface Props {
  fieldDescription: FieldDescription
  renderInfos: Properties
  onValueChangeField: (value: any, key: string) => void
}


const FieldInput = ({ fieldDescription, renderInfos, onValueChangeField }: Props) => {
  const { name, type, label, options, className, description } = fieldDescription


  return (
    <DynamicInput
      type={type}
      label={label}
      value={renderInfos[name]}
      options={options}
      className={className}
      description={description}
      onChange={(v) => onValueChangeField(v, name)}
    />
  )
}


export default FieldInput

// packages/angular/src/components/FieldInput.ts
import { Component, Input, Output, EventEmitter } from "@angular/core"
import { CommonModule } from '@angular/common'
import { DynamicInput } from './DynamicInput'
import { FieldDescription, Properties } from "@dynamic-field-kit/core"

@Component({
  selector: "dfk-field-input",
  standalone: true,
  imports: [CommonModule, DynamicInput],
  template: `
    <dfk-dynamic-input
      [type]="fieldDescription.type"
      [value]="renderInfos[fieldDescription.name]"
      [label]="fieldDescription.label"
      [placeholder]="fieldDescription.placeholder"
      [required]="fieldDescription.required"
      [description]="fieldDescription.description"
      [options]="fieldDescription.options"
      [className]="fieldDescription.className"
      (onChange)="onValueChangeField.emit({ value: $event, key: fieldDescription.name })"
    ></dfk-dynamic-input>
  `,
})
export class FieldInput {
  @Input() fieldDescription!: FieldDescription
  @Input() renderInfos!: Properties
  @Output() onValueChangeField = new EventEmitter<any>()
}
